from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

import pytest

from rodex.app_server_contract import (
    SUPPORTED_CODEX_APP_SERVER_VERSION,
    RodexAppServerCompatibilityError,
    require_supported_app_server,
)


def _load_schema(schema_root: Path, relative_path: str) -> dict[str, Any]:
    return json.loads((schema_root / relative_path).read_text(encoding="utf-8"))


def _characterize_schema(schema_root: Path) -> dict[str, object]:
    request_id = _load_schema(schema_root, "RequestId.json")
    server_request = _load_schema(schema_root, "ServerRequest.json")
    thread_read = _load_schema(schema_root, "v2/ThreadReadResponse.json")
    turn_start = _load_schema(schema_root, "v2/TurnStartParams.json")
    turn_start_response = _load_schema(schema_root, "v2/TurnStartResponse.json")
    turn_steer = _load_schema(schema_root, "v2/TurnSteerParams.json")
    turn_interrupt = _load_schema(schema_root, "v2/TurnInterruptParams.json")
    definitions = thread_read["definitions"]
    agent_message = next(
        option
        for option in definitions["ThreadItem"]["oneOf"]
        if option["title"] == "AgentMessageThreadItem"
    )
    return {
        "codex_cli_version": SUPPORTED_CODEX_APP_SERVER_VERSION,
        "generated_with": "codex app-server generate-json-schema --experimental",
        "request_id_types": sorted(option["type"] for option in request_id["anyOf"]),
        "thread_required_fields": definitions["Thread"]["required"],
        "thread_statuses": sorted(
            option["properties"]["type"]["enum"][0]
            for option in definitions["ThreadStatus"]["oneOf"]
        ),
        "turn_statuses": definitions["TurnStatus"]["enum"],
        "agent_message_phases": sorted(
            option["enum"][0] for option in definitions["MessagePhase"]["oneOf"]
        ),
        "agent_message_phase_required": "phase" in agent_message["required"],
        "agent_message_phase_nullable": any(
            option.get("type") == "null"
            for option in agent_message["properties"]["phase"]["anyOf"]
        ),
        "file_change_statuses": definitions["PatchApplyStatus"]["enum"],
        "turn_start_required_params": turn_start["required"],
        "turn_start_response_required_fields": turn_start_response["required"],
        "turn_steer_required_params": turn_steer["required"],
        "turn_interrupt_required_params": turn_interrupt["required"],
        "server_request_methods": sorted(
            option["properties"]["method"]["enum"][0] for option in server_request["oneOf"]
        ),
    }


@pytest.mark.evolutionary_regression
def test_checked_in_contract_is_generated_from_the_installed_supported_cli(
    tmp_path: Path,
) -> None:
    """Current evidence is the schema generated by the exact supported Codex build."""
    codex = shutil.which("codex")
    if codex is None:
        pytest.skip("Codex CLI is not installed")
    version = subprocess.run(
        [codex, "--version"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if version != f"codex-cli {SUPPORTED_CODEX_APP_SERVER_VERSION}":
        pytest.skip(f"installed CLI is outside this contract: {version}")
    schema_root = tmp_path / "schema"
    subprocess.run(
        [
            codex,
            "app-server",
            "generate-json-schema",
            "--experimental",
            "--out",
            str(schema_root),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    fixture_path = (
        Path(__file__).parent / "fixtures" / "codex_app_server_0_147_contract.json"
    )
    checked_in = json.loads(fixture_path.read_text(encoding="utf-8"))

    assert checked_in == _characterize_schema(schema_root)


def test_live_initialize_metadata_is_the_exact_control_compatibility_gate() -> None:
    assert (
        require_supported_app_server({"userAgent": "rodex-control/0.147.0 (Linux; x86_64)"})
        == "0.147.0"
    )

    with pytest.raises(RodexAppServerCompatibilityError, match=r"live server is 0\.148\.0"):
        require_supported_app_server({"userAgent": "rodex-control/0.148.0 (Linux)"})

    with pytest.raises(RodexAppServerCompatibilityError, match="no recognized"):
        require_supported_app_server({})
