from __future__ import annotations

import ast
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

import pytest

from rodex.app_server_contract import (
    CODEX_APP_SERVER,
    RODEX_CONTROL_APP_SERVER_CLIENT,
    RODEX_RUNTIME_APP_SERVER_CLIENT,
    AppServerClientInfo,
    RodexAppServerCompatibilityError,
)


def _load_schema(schema_root: Path, relative_path: str) -> dict[str, Any]:
    return json.loads((schema_root / relative_path).read_text(encoding="utf-8"))


def _characterize_schema(schema_root: Path) -> dict[str, object]:
    request_id = _load_schema(schema_root, "RequestId.json")
    server_request = _load_schema(schema_root, "ServerRequest.json")
    thread_read = _load_schema(schema_root, "v2/ThreadReadResponse.json")
    turn_start = _load_schema(schema_root, "v2/TurnStartParams.json")
    turn_start_response = _load_schema(schema_root, "v2/TurnStartResponse.json")
    turn_steer = _load_schema(schema_root, "v2/TurnSteerParams.json")
    turn_interrupt = _load_schema(schema_root, "v2/TurnInterruptParams.json")
    user_input_request = _load_schema(schema_root, "ToolRequestUserInputParams.json")
    user_input_response = _load_schema(schema_root, "ToolRequestUserInputResponse.json")
    definitions = thread_read["definitions"]
    agent_message = next(
        option
        for option in definitions["ThreadItem"]["oneOf"]
        if option["title"] == "AgentMessageThreadItem"
    )
    user_message = next(
        option
        for option in definitions["ThreadItem"]["oneOf"]
        if option["title"] == "UserMessageThreadItem"
    )
    return {
        "codex_cli_version": CODEX_APP_SERVER.minimum_supported_version,
        "generated_with": "codex app-server generate-json-schema --experimental",
        "request_id_types": sorted(option["type"] for option in request_id["anyOf"]),
        "thread_required_fields": definitions["Thread"]["required"],
        "thread_statuses": sorted(
            option["properties"]["type"]["enum"][0]
            for option in definitions["ThreadStatus"]["oneOf"]
        ),
        "turn_statuses": definitions["TurnStatus"]["enum"],
        "agent_message_phases": sorted(
            option["enum"][0] for option in definitions["MessagePhase"]["oneOf"]
        ),
        "agent_message_phase_required": "phase" in agent_message["required"],
        "agent_message_phase_nullable": any(
            option.get("type") == "null"
            for option in agent_message["properties"]["phase"]["anyOf"]
        ),
        "file_change_statuses": definitions["PatchApplyStatus"]["enum"],
        "turn_start_required_params": turn_start["required"],
        "turn_start_client_message_id_types": sorted(
            turn_start["properties"]["clientUserMessageId"]["type"]
        ),
        "turn_start_response_required_fields": turn_start_response["required"],
        "turn_steer_required_params": turn_steer["required"],
        "turn_steer_client_message_id_types": sorted(
            turn_steer["properties"]["clientUserMessageId"]["type"]
        ),
        "user_message_client_id_types": sorted(
            user_message["properties"]["clientId"]["type"]
        ),
        "user_message_client_id_required": "clientId" in user_message["required"],
        "user_input_request_required_params": user_input_request["required"],
        "user_input_response_required_params": user_input_response["required"],
        "turn_interrupt_required_params": turn_interrupt["required"],
        "server_request_methods": sorted(
            option["properties"]["method"]["enum"][0] for option in server_request["oneOf"]
        ),
    }


@pytest.mark.evolutionary_regression
def test_checked_in_contract_is_generated_from_the_installed_supported_cli(
    tmp_path: Path,
) -> None:
    """Current evidence is the schema generated by the exact supported Codex build."""
    codex = shutil.which("codex")
    if codex is None:
        pytest.skip("Codex CLI is not installed")
    version = subprocess.run(
        [codex, "--version"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if version != f"codex-cli {CODEX_APP_SERVER.minimum_supported_version}":
        pytest.skip(f"installed CLI is outside this contract: {version}")
    schema_root = tmp_path / "schema"
    subprocess.run(
        [
            codex,
            "app-server",
            "generate-json-schema",
            "--experimental",
            "--out",
            str(schema_root),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    fixture_path = (
        Path(__file__).parent / "fixtures" / "codex_app_server_0_147_contract.json"
    )
    checked_in = json.loads(fixture_path.read_text(encoding="utf-8"))

    assert checked_in == _characterize_schema(schema_root)


def test_live_initialize_metadata_accepts_the_minimum_and_newer_versions() -> None:
    assert (
        CODEX_APP_SERVER.require_supported_version(
            {"userAgent": "rodex-control/0.147.0 (Linux; x86_64)"}
        )
        == "0.147.0"
    )

    assert (
        CODEX_APP_SERVER.require_supported_version(
            {"userAgent": "rodex-control/0.148.0 (Linux)"}
        )
        == "0.148.0"
    )

    assert (
        CODEX_APP_SERVER.require_supported_version(
            {"userAgent": "rodex-control/1.0.0 (Linux)"}
        )
        == "1.0.0"
    )


def test_live_initialize_metadata_rejects_downgrades_and_unknown_versions() -> None:
    with pytest.raises(
        RodexAppServerCompatibilityError,
        match=r"requires Codex App Server 0\.147\.0 or newer; live server is 0\.146\.0",
    ):
        CODEX_APP_SERVER.require_supported_version(
            {"userAgent": "rodex-control/0.146.0 (Linux)"}
        )

    with pytest.raises(
        RodexAppServerCompatibilityError, match="unrecognized Codex version"
    ):
        CODEX_APP_SERVER.require_supported_version(
            {"userAgent": "rodex-control/development (Linux)"}
        )

    with pytest.raises(RodexAppServerCompatibilityError, match="no recognized"):
        CODEX_APP_SERVER.require_supported_version({})


def test_contract_owns_process_and_handshake_messages(tmp_path: Path) -> None:
    socket_path = tmp_path / "app.sock"

    assert CODEX_APP_SERVER.command("codex", socket_path) == (
        "codex",
        "app-server",
        "--listen",
        f"unix://{socket_path}",
    )
    assert CODEX_APP_SERVER.initialize_request(
        "request-1", RODEX_CONTROL_APP_SERVER_CLIENT
    ) == {
        "method": CODEX_APP_SERVER.initialize_method,
        "id": "request-1",
        "params": {
            "clientInfo": {
                "name": "rodex-control",
                "title": "Rodex Control",
                "version": RODEX_CONTROL_APP_SERVER_CLIENT.version,
            }
        },
    }
    assert CODEX_APP_SERVER.initialized_notification() == {
        "method": CODEX_APP_SERVER.initialized_method,
        "params": {},
    }
    assert RODEX_RUNTIME_APP_SERVER_CLIENT.name == "rodex"


def test_contract_adds_experimental_capability_in_one_place() -> None:
    client = AppServerClientInfo("test", "Test", "1")

    assert CODEX_APP_SERVER.initialize_params(client, experimental_api=True) == {
        "clientInfo": {"name": "test", "title": "Test", "version": "1"},
        "capabilities": {"experimentalApi": True},
    }


def test_app_server_method_vocabulary_has_one_production_owner() -> None:
    source_root = Path(__file__).parents[1] / "src" / "rodex"
    owned_methods = {
        CODEX_APP_SERVER.initialize_method,
        CODEX_APP_SERVER.initialized_method,
        CODEX_APP_SERVER.thread_loaded_list_method,
        CODEX_APP_SERVER.thread_read_method,
        CODEX_APP_SERVER.thread_status_changed_method,
        CODEX_APP_SERVER.turn_start_method,
        CODEX_APP_SERVER.turn_started_method,
        CODEX_APP_SERVER.turn_steer_method,
        CODEX_APP_SERVER.turn_interrupt_method,
        CODEX_APP_SERVER.turn_completed_method,
    }
    duplicates: list[tuple[str, str]] = []
    for path in source_root.glob("*.py"):
        if path.name == "app_server_contract.py":
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        duplicates.extend(
            (path.name, node.value)
            for node in ast.walk(tree)
            if isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and node.value in owned_methods
        )

    assert duplicates == []
